name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Backend Image
      - name: Build Backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend

      # Build Frontend Image
      - name: Build Frontend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend

      # Push Images
      - name: Push Backend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Push Frontend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # Deploy to VM
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd crud-dd-task-mean-app
            docker-compose pull
            docker-compose down
            docker-compose up -d
